-- 개인정보 수집·이용 동의 기록 (일반교사/담당교사 최초 로그인 시)
-- 학교·역할별 동의 시점을 DB에 저장 (감사·분쟁 대응용)

CREATE TABLE IF NOT EXISTS consent_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_code text NOT NULL,
  role text NOT NULL,
  agreed_at timestamptz DEFAULT now(),
  ip inet,
  user_agent text
);

COMMENT ON TABLE consent_log IS '개인정보 수집·이용 동의 기록';
COMMENT ON COLUMN consent_log.school_code IS 'NEIS 학교코드';
COMMENT ON COLUMN consent_log.role IS 'teacher | manager';
COMMENT ON COLUMN consent_log.agreed_at IS '동의 시각';
COMMENT ON COLUMN consent_log.ip IS '동의 시점 IP (선택)';
COMMENT ON COLUMN consent_log.user_agent IS '동의 시점 User-Agent (선택)';

CREATE INDEX IF NOT EXISTS idx_consent_log_school_role ON consent_log (school_code, role);

-- RLS: anon은 접근 불가. 기록은 Netlify Function(service_role)에서만 INSERT.
ALTER TABLE consent_log ENABLE ROW LEVEL SECURITY;
